# base image
FROM python:3.7.2-alpine


# POSTGRESQL dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# make and set workdir
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements.txt
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copy start script
COPY ./start.sh /usr/src/app/start.sh
RUN chmod +x /usr/src/app/start.sh


# add app
COPY . /usr/src/app

# run server
CMD ["/usr/src/app/start.sh"]